language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"
before_script:
  - composer self-update
  - composer update --no-interaction $COMPOSER_OPTS
script:
  - vendor/bin/phing
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
