language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"
before_script:
  - composer self-update
  - composer update --no-interaction $COMPOSER_OPTS
script:
  - vendor/bin/phing
  - if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then vendor/bin/humbug -b; fi
